name: Rust

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Install libudev
      run: sudo apt install libudev-dev libudev0
    - uses: actions/checkout@v3
    - name: Build
      run: cargo build --verbose
